Declare
user_id number(10);

begin
	if(:P10_USER_TYPE = 'FACULTY') then
		user_id := :P10_BORROWER_FACULTY;
          insert into LMS_BOOK_ISSUE(BOOK_ISSUE_ID,BOOK_ID,BORROWER_ID,ISSUED_BY,BORROWED_FROM_DATE,BORROWED_TO_DATE,BORROWER_TYPE,BOOK_RT_STATUS)
    values(LMS_BOOK_ISSUE_SEQ.nextval,:P10_BOOK_TITLE,user_id, 1, :P10_BOROWED_DATE,:P10_RETURN_DATE,'FACULTY',1 );
    
    update LMS_BOOK_DETAIL set BOOK_NO_OF_COPIES_CURRENT = BOOK_NO_OF_COPIES_CURRENT-1 where BOOK_ID=:P10_BOOK_TITLE;
    
	else
		user_id := :P10_STUDENT;
        insert into LMS_BOOK_ISSUE(BOOK_ISSUE_ID,BOOK_ID,BORROWER_ID,ISSUED_BY,BORROWED_FROM_DATE,BORROWED_TO_DATE,BORROWER_TYPE,BOOK_RT_STATUS)
    values(LMS_BOOK_ISSUE_SEQ.nextval,:P10_BOOK_TITLE,user_id, 1, :P10_BOROWED_DATE,:P10_RETURN_DATE,'STUDENT',1 );
    
    update LMS_BOOK_DETAIL set BOOK_NO_OF_COPIES_CURRENT = BOOK_NO_OF_COPIES_CURRENT-1 where BOOK_ID=:P10_BOOK_TITLE;
    
	end if;
    
    

end;
