select LBI.BOOK_ISSUE_ID||'---'||
(select STAFF_NAME from LMS_STAFF_DETAIL where STAFF_ID =
(select LB.ENTITY_OWNER_FK from LMS_BORROWER LB WHERE LB.BORROWER_ID=LBI.BORROWER_ID)) as display_value,
LBI.BOOK_ISSUE_ID as return_value from LMS_BOOK_ISSUE LBI where LBI.BORROWER_TYPE='FACULTY' and BOOK_RT_STATUS =1 